import type { Asset } from '@/lib/types/layers';

/**
 * Pre-built overlay templates for the Assets panel
 */
export const PREBUILT_OVERLAYS: Asset[] = [
  {
    id: 'overlay-cherry-blossoms',
    name: 'Cherry Blossoms',
    type: 'template',
    category: 'overlays',
    thumbnail: '/CherryBlossoms.mp4', // Video thumbnail
    createdAt: new Date('2024-01-01'),
    data: {
      description: 'Beautiful cherry blossom overlay with animated video background - perfect for nature and calm stream aesthetics',
      shapes: [
        // Video background
        {
          id: 'cherry-video',
          type: 'video',
          x: 0,
          y: 0,
          width: 1920,
          height: 1080,
          videoUrl: '/CherryBlossoms.mp4',
          opacity: 0.7,
          loop: true,
          autoplay: true,
        },
        // Overlay frame/border
        {
          id: 'cherry-frame',
          type: 'rect',
          x: 0,
          y: 0,
          width: 1920,
          height: 1080,
          fill: 'transparent',
          stroke: 'rgba(255, 192, 203, 0.5)', // Pink border
          strokeWidth: 8,
        },
        // Top gradient overlay for text readability
        {
          id: 'cherry-top-gradient',
          type: 'rect',
          x: 0,
          y: 0,
          width: 1920,
          height: 300,
          fill: 'linear-gradient(180deg, rgba(0, 0, 0, 0.6) 0%, transparent 100%)',
        },
        // Bottom gradient overlay for text readability
        {
          id: 'cherry-bottom-gradient',
          type: 'rect',
          x: 0,
          y: 780,
          width: 1920,
          height: 300,
          fill: 'linear-gradient(0deg, rgba(0, 0, 0, 0.6) 0%, transparent 100%)',
        },
        // Decorative title area
        {
          id: 'cherry-title-bg',
          type: 'rect',
          x: 660,
          y: 80,
          width: 600,
          height: 120,
          fill: 'rgba(255, 192, 203, 0.15)',
          stroke: 'rgba(255, 192, 203, 0.6)',
          strokeWidth: 2,
          cornerRadius: 15,
          shadowColor: 'rgba(0, 0, 0, 0.3)',
          shadowBlur: 20,
        },
        // Stream title text
        {
          id: 'cherry-title',
          type: 'text',
          x: 960,
          y: 140,
          text: 'YOUR STREAM TITLE',
          fontSize: 48,
          fontFamily: 'Arial',
          fontStyle: 'bold',
          fill: '#ffffff',
          align: 'center',
          verticalAlign: 'middle',
          shadowColor: 'rgba(0, 0, 0, 0.8)',
          shadowBlur: 10,
          shadowOffset: { x: 0, y: 2 },
        },
        // Webcam placeholder
        {
          id: 'cherry-webcam-border',
          type: 'rect',
          x: 1420,
          y: 680,
          width: 420,
          height: 320,
          fill: 'rgba(0, 0, 0, 0.3)',
          stroke: 'rgba(255, 192, 203, 0.8)',
          strokeWidth: 4,
          cornerRadius: 20,
          shadowColor: 'rgba(0, 0, 0, 0.5)',
          shadowBlur: 25,
        },
        // Webcam label
        {
          id: 'cherry-webcam-label',
          type: 'text',
          x: 1630,
          y: 840,
          text: 'WEBCAM',
          fontSize: 24,
          fontFamily: 'Arial',
          fontStyle: 'bold',
          fill: 'rgba(255, 255, 255, 0.5)',
          align: 'center',
          verticalAlign: 'middle',
        },
      ],
      layers: [
        {
          id: 'cherry-video',
          name: 'Cherry Blossoms Video',
          type: 'image',
          visible: true,
          locked: false,
          opacity: 0.7,
          blendMode: 'normal',
        },
        {
          id: 'cherry-frame',
          name: 'Border Frame',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'cherry-top-gradient',
          name: 'Top Gradient',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'cherry-bottom-gradient',
          name: 'Bottom Gradient',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'cherry-title-bg',
          name: 'Title Background',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'cherry-title',
          name: 'Stream Title',
          type: 'text',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'cherry-webcam-border',
          name: 'Webcam Border',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'cherry-webcam-label',
          name: 'Webcam Label',
          type: 'text',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
      ],
      tags: ['overlay', 'nature', 'cherry blossoms', 'video', 'aesthetic', 'calm', 'pink'],
      usage: 'A beautiful nature-themed overlay with animated cherry blossoms. Perfect for calm, aesthetic streams. Edit the title text and webcam position to match your layout. Adjust video opacity for desired effect.',
    },
  },
];

/**
 * Pre-built widget templates for the Assets panel
 */
export const PREBUILT_WIDGETS: Asset[] = [
  {
    id: 'widget-alert-box',
    name: 'Alert Box',
    type: 'template',
    category: 'widgets',
    thumbnail: '/assets/widgets/alert-box-thumb.png', // You can update this with actual thumbnail
    createdAt: new Date('2024-01-01'),
    data: {
      description: 'Classic stream alert box for followers, subs, donations, and raids',
      shapes: [
        // Background container
        {
          id: 'alert-bg',
          type: 'rect',
          x: 0,
          y: 0,
          width: 800,
          height: 300,
          fill: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
          stroke: '#ffffff',
          strokeWidth: 4,
          cornerRadius: 20,
          shadowColor: 'rgba(0, 0, 0, 0.5)',
          shadowBlur: 30,
          shadowOffset: { x: 0, y: 10 },
          shadowOpacity: 0.8,
        },
        // Inner glow effect
        {
          id: 'alert-inner-glow',
          type: 'rect',
          x: 8,
          y: 8,
          width: 784,
          height: 284,
          fill: 'transparent',
          stroke: 'rgba(255, 255, 255, 0.3)',
          strokeWidth: 2,
          cornerRadius: 16,
        },
        // Icon/Avatar placeholder circle
        {
          id: 'alert-icon',
          type: 'circle',
          x: 100,
          y: 150,
          radius: 60,
          fill: '#ffffff',
          stroke: '#667eea',
          strokeWidth: 4,
          shadowColor: 'rgba(0, 0, 0, 0.3)',
          shadowBlur: 15,
        },
        // Alert title text
        {
          id: 'alert-title',
          type: 'text',
          x: 400,
          y: 80,
          text: 'NEW FOLLOWER!',
          fontSize: 48,
          fontFamily: 'Arial',
          fontStyle: 'bold',
          fill: '#ffffff',
          align: 'center',
          verticalAlign: 'middle',
          shadowColor: 'rgba(0, 0, 0, 0.5)',
          shadowBlur: 10,
          shadowOffset: { x: 0, y: 4 },
        },
        // Username/message text
        {
          id: 'alert-message',
          type: 'text',
          x: 400,
          y: 150,
          text: 'Username',
          fontSize: 36,
          fontFamily: 'Arial',
          fontStyle: 'normal',
          fill: '#ffffff',
          align: 'center',
          verticalAlign: 'middle',
          shadowColor: 'rgba(0, 0, 0, 0.3)',
          shadowBlur: 6,
        },
        // Subtitle/thank you text
        {
          id: 'alert-subtitle',
          type: 'text',
          x: 400,
          y: 220,
          text: 'Thank you for the support!',
          fontSize: 24,
          fontFamily: 'Arial',
          fontStyle: 'italic',
          fill: 'rgba(255, 255, 255, 0.9)',
          align: 'center',
          verticalAlign: 'middle',
        },
        // Decorative accent line top
        {
          id: 'alert-accent-top',
          type: 'rect',
          x: 200,
          y: 40,
          width: 400,
          height: 4,
          fill: '#ffffff',
          cornerRadius: 2,
        },
        // Decorative accent line bottom
        {
          id: 'alert-accent-bottom',
          type: 'rect',
          x: 200,
          y: 256,
          width: 400,
          height: 4,
          fill: '#ffffff',
          cornerRadius: 2,
        },
      ],
      layers: [
        {
          id: 'alert-bg',
          name: 'Background',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'alert-inner-glow',
          name: 'Inner Glow',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'alert-accent-top',
          name: 'Accent Line Top',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'alert-accent-bottom',
          name: 'Accent Line Bottom',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'alert-icon',
          name: 'Icon/Avatar',
          type: 'shape',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'alert-title',
          name: 'Alert Title',
          type: 'text',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'alert-message',
          name: 'Username/Message',
          type: 'text',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
        {
          id: 'alert-subtitle',
          name: 'Subtitle',
          type: 'text',
          visible: true,
          locked: false,
          opacity: 1,
          blendMode: 'normal',
        },
      ],
      tags: ['alert', 'notification', 'follower', 'subscriber', 'donation'],
      usage: 'Customize the colors, text, and icon to match your stream branding. Works for followers, subscribers, donations, raids, and more.',
    },
  },
];
